spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/sample?rewriteBatchedStatements=true
        username: dbuser
        password: dbuser
        max-wait: 1000
        max-active: 50
        test-on-borrow: false
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        database: MySQL
        show-sql: true

broker:
    bootstrapServer: 127.0.0.1:8092
    producer:
        linger-time-ms: 0

